version: "3.8"


networks:
  default:
    name: default-internal-network


volumes:
  redis-data:
    name: redis-data
    driver: local
  postgres-data:
    name: postgres-data
    driver: local
  influx-data:
    name: influx-data
    driver: local


services:

  crawler:
    container_name: crawler
    image: crawler
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/jackrawler
    networks:
      - default
    expose:
      - 22
    working_dir: /home/jackrawler
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    restart: always

  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    networks:
      - default
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./.docker/postgres-data-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      # connect to the database of Pj. " wetrade "
      POSTGRES_DB: wetrade
      POSTGRES_USER: wetrade
      POSTGRES_PASSWORD: 9BQGu#3YgfUX73Pl

  influxdb:
    container_name: influxdb
    image: influxdb:1.7-alpine
    networks:
      - default
    ports:
      - 8088:8088
    volumes:
      - influx-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: jackrawler
