version: "3.8"


networks:
  default:
    name: JNeT


volumes:
  jira-data:
    name: jira-data
  bitbucket-data:
    name: bitbucket-data
  confluence-data:
    name: confluence-data
  postgres-data:
    name: postgres-data


services:
  jira:
    image: cptactionhank/atlassian-jira:7.9.2
    container_name: jira
    depends_on:
      - postgres
    volumes:
      - jira-data:/var/atlassian/jira
    restart: always

  bitbucket:
    image: atlassian/bitbucket-server:5.10.1
    container_name: bitbucket
    depends_on:
      - postgres
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    restart: always

  confluence:
    image: cptactionhank/atlassian-confluence:6.9.0
    container_name: confluence
    depends_on:
      - postgres
    volumes:
      - confluence-data:/var/atlassian/confluence
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always

  jira-nginx:
    image: nginx:latest
    container_name: jira-nginx
    ports:
      - 80:80
    links:
      - jira
      - bitbucket
      - confluence
    volumes:
      - ./:/src
    environment:
      DOMAIN: ${DOMAIN}
    restart: always
    command: ./src/scripts/run_nginx.sh
